elements = {
    'username': {'method': 'name',
                 'value': 'username',
                 'item_order': 0},
    'password': {'method': 'name',
                 'value': 'password',
                 'item_order': 0},
    'login_btn': {'method': 'id',
                  'value': 'm_login_signin_submit'},

    'article_table': {'method': 'id',
                      'value': 'table'},
    'article_edit_button': {'method': 'tag_name',
                            'value': 'a',
                            'item_order': 2},
    'unit': {'method': 'id',
             'value': 'unit'},
    'no': {'method': 'id',
           'value': 'No'},
    'comment': {'method': 'id',
                'value': 'comment'},
    'name': {'method': 'id',
             'value': 'name'},
    'save': {'method': 'class_name',
             'value': 'btn-primary',
             'item_order': 0},
    'cancel': {'method': 'class_name',
               'value': 'btn-secondary',
               'item_order': 2},
    'confirmation_pop_up': {
        'method': 'id',
        'value': 'swal2-title'},

    'confirm_pop': {'method': 'class_name',
                    'value': 'btn-success',
                    'item_order': 0},
    'confirm_cancel': {'method': 'class_name',
                       'value': 'btn-secondary',
                       'item_order': 0}
}
